"""empty message

Revision ID: 768f034b1ca1
Revises: f7e5bb04027a
Create Date: 2023-08-07 17:49:09.001329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768f034b1ca1'
down_revision = 'f7e5bb04027a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=False))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
